### ISSUE TITLE
Software pop-up position problem

### ISSUE THREAD

**Issue by yFhope** [m2jean/ToothTray#8]
Hi！After right-clicking, the pop-up menu is located in the taskbar, can it appear on the top of the taskbar, so that it looks more reasonable!

Have you considered left-clicking and then the selection menu appears? Or offer similar setup options

**Comment by m2jean** [comment]
All the Windows builtin tray icons show their context menu on top of the taskbar so I think that's the convention. Is there something it is blocking that you would like to look at while the menu is open?

Since left clicking does nothing now, I can update the code to make the menu open on both left and right clicks
